packages:
  - packages/*

catalog:
  '@antfu/eslint-config': ^4.16.2
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@commitlint/types': ^19.8.1
  '@eslint-react/eslint-plugin': ^1.52.2
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.3.0
  '@rslib/core': ^0.10.5
  '@types/node': ^24.0.12
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  eslint: ^9.30.1
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  lint-staged: ^16.1.2
  react: ^18.3.1
  react-dom: ^18.3.1
  simple-git-hooks: ^2.13.0
  typescript: ~5.8.3
  vite: ^7.0.4
  vitest: ^3.2.4
  zx: ^8.2.4
  '@rsbuild/plugin-react': ^1.3.4
