packages:
  - 'packages/*'
  - website
  - scripts
catalog:
  '@antfu/eslint-config': ^3.11.2
  '@commitlint/cli': ^19.6.0
  '@commitlint/config-conventional': ^19.6.0
  '@eslint-react/eslint-plugin': ^1.17.2
  '@rollup/plugin-commonjs': ^28.0.1
  '@rollup/plugin-node-resolve': ^15.3.0
  '@testing-library/jest-dom': ^6.6.3
  '@testing-library/react': ^16.0.1
  '@types/node': ^22.10.1
  '@types/react': ^18.3.12
  '@types/react-dom': ^18.3.1
  chalk: ^5.3.0
  cross-spawn: ^7.0.6
  dumi: ^2.4.14
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.14
  fast-glob: ^3.3.2
  father: ^4.5.1
  ora: ^8.1.1
  react: ^18.3.1
  react-dom: ^18.3.1
  rollup: ^4.28.0
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  typescript: ~5.4.5
  vite: ^5.4.11
  vitest: ^2.1.6
  zx: ^8.2.4
